<?php

declare(strict_types=1);

require dirname(__DIR__, 2) . '/vendor/autoload.php';

use Goal\Legacy\Core\Bootstrap\Bootstrap;
use Goal\Legacy\Devtools\CommandRegistry;
use Goal\Legacy\Devtools\ConsoleApplication;
use Goal\Legacy\Devtools\StreamConsoleOutput;
use Goal\Legacy\Devtools\Commands\CoreSelfCheckCommand;
use Goal\Legacy\Devtools\Commands\ContentListCommand;
use Goal\Legacy\Devtools\Commands\DoctorCommand;
use Goal\Legacy\Devtools\Commands\InspectConfigurationCommand;
use Goal\Legacy\Devtools\Commands\InspectLogsCommand;
use Goal\Legacy\Devtools\Commands\ListModulesCommand;
use Goal\Legacy\Devtools\Commands\PersistenceSelfCheckCommand;
use Goal\Legacy\Devtools\Commands\TimeSelfCheckCommand;
use Goal\Legacy\Devtools\Commands\NationListCommand;
use Goal\Legacy\Devtools\Commands\NationSelfCheckCommand;
use Goal\Legacy\Devtools\Commands\CompetitionListCommand;
use Goal\Legacy\Devtools\Commands\ClubListCommand;
use Goal\Legacy\Devtools\Commands\PlayerCreateDemoCommand;
use Goal\Legacy\Devtools\Commands\WorldSelfCheckCommand;
use Goal\Legacy\Devtools\Commands\TransferSelfCheckCommand;
use Goal\Legacy\Devtools\Commands\MatchSelfCheckCommand;
use Goal\Legacy\Devtools\Commands\CareerSelfCheckCommand;
use Goal\Legacy\Devtools\Commands\CareerSeasonAuditCommand;
use Goal\Legacy\Devtools\Commands\PopulationSelfCheckCommand;
use Goal\Legacy\Devtools\Commands\RecruitmentSelfCheckCommand;
use Goal\Legacy\Devtools\Commands\CareerTransferSelfCheckCommand;
use Goal\Legacy\Devtools\Commands\CareerMultiSeasonAuditCommand;
use Goal\Legacy\Devtools\Commands\CareerNewCommand;
use Goal\Legacy\Devtools\Commands\CareerHomeCommand;
use Goal\Legacy\Devtools\Commands\CareerContinueCommand;
use Goal\Legacy\Devtools\Commands\CareerActionCommand;
use Goal\Legacy\Devtools\Commands\CareerViewCommand;
use Goal\Legacy\Devtools\Commands\CareerWorldCommand;
use Goal\Legacy\Devtools\Commands\CareerPlayCommand;
use Goal\Legacy\Devtools\Commands\CareerNewsCommand;

$projectRoot = dirname(__DIR__, 2);
$services = (new Bootstrap())->create($projectRoot);
$commands = new CommandRegistry();
$commands->register(new DoctorCommand($services, $projectRoot));
$commands->register(new ListModulesCommand($services));
$commands->register(new CoreSelfCheckCommand($services));
$commands->register(new InspectConfigurationCommand($services));
$commands->register(new InspectLogsCommand($services, $projectRoot));
$commands->register(new TimeSelfCheckCommand($services));
$commands->register(new PersistenceSelfCheckCommand($services));
$commands->register(new ContentListCommand($services));
$commands->register(new NationListCommand($services));
$commands->register(new NationSelfCheckCommand($services));
$commands->register(new CompetitionListCommand($services));
$commands->register(new ClubListCommand($services));
$commands->register(new PlayerCreateDemoCommand($services));
$commands->register(new WorldSelfCheckCommand($services));
$commands->register(new TransferSelfCheckCommand($services));
$commands->register(new MatchSelfCheckCommand($services));
$commands->register(new CareerSelfCheckCommand($services));
$commands->register(new CareerSeasonAuditCommand($services));
$commands->register(new PopulationSelfCheckCommand($services));
$commands->register(new RecruitmentSelfCheckCommand($services));
$commands->register(new CareerTransferSelfCheckCommand($services));
$commands->register(new CareerMultiSeasonAuditCommand($services));
$commands->register(new CareerNewCommand($services, $projectRoot));
$commands->register(new CareerHomeCommand($services));
$commands->register(new CareerContinueCommand($services));
$commands->register(new CareerActionCommand($services));
$commands->register(new CareerViewCommand($services));
$commands->register(new CareerWorldCommand($services));
$commands->register(new CareerNewsCommand($services));
$commands->register(new CareerPlayCommand($services));

$application = new ConsoleApplication($commands);
exit($application->run($argv, new StreamConsoleOutput(STDOUT, STDERR)));
